#!/usr/bin/env python3
"""wisci.py — deterministic core for the WISCI context framework.

Subcommands (all JSON to stdout unless noted):
  status <file>     Staleness classification for one context file
  scan              Classification for every file in .wisci/
  index             Regenerate .wisci/handoff.md from leaf frontmatter
  index --list      Print handoff streams as JSON without writing
  session-status    One-line store summary for hooks (plain text, empty if no store)
  structure-hash    Print current repo structure hash (stamped into primer frontmatter)
  test              Run self-tests against a throwaway git repo

Python 3.8+ stdlib only. No third-party dependencies.
"""

import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

GENERATED_MARKER = "Generated by wisci.py — do not edit."


# ---------- git plumbing ----------

def git(args, cwd):
    """Run git, return stdout (stripped). Returns None on failure."""
    try:
        r = subprocess.run(["git"] + args, cwd=cwd, capture_output=True, text=True)
    except FileNotFoundError:
        return None
    if r.returncode != 0:
        return None
    return r.stdout.strip()


def repo_root(start):
    top = git(["rev-parse", "--show-toplevel"], cwd=start)
    return top if top else os.path.abspath(start)


# ---------- parsing ----------

REF_LINE = re.compile(r"^\s*[-*]\s*`([^`]+)`")
IMPLICIT_LINE_SUFFIX = re.compile(r":\d+(-\d+)?$")


def parse_references(text):
    """Extract paths from the `## References` manifest section."""
    refs = []
    in_refs = False
    for line in text.splitlines():
        if line.startswith("## "):
            in_refs = line.strip().lower() == "## references"
            continue
        if in_refs:
            m = REF_LINE.match(line)
            if m:
                path = IMPLICIT_LINE_SUFFIX.sub("", m.group(1).strip())
                if path and path not in refs:
                    refs.append(path)
    return refs


def parse_frontmatter(text):
    """Minimal YAML frontmatter parser: flat `key: value` string pairs only."""
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    fm = {}
    for line in text[4:end].splitlines():
        if ":" in line and not line.lstrip().startswith("#"):
            key, _, value = line.partition(":")
            fm[key.strip()] = value.strip().strip("\"'")
    return fm


# ---------- structure hash ----------

def structure_hash(root):
    """Hash of the repo's directory topology (detects new/removed dirs)."""
    listed = git(["ls-files"], cwd=root)
    if listed is None:
        return None
    dirs = set()
    for f in listed.splitlines():
        d = os.path.dirname(f)
        while d:
            dirs.add(d)
            d = os.path.dirname(d)
    return hashlib.sha256("\n".join(sorted(dirs)).encode()).hexdigest()[:16]


# ---------- staleness ----------

def age_days(iso_or_mtime):
    if iso_or_mtime is None:
        return None
    if isinstance(iso_or_mtime, str):
        try:
            then = datetime.fromisoformat(iso_or_mtime)
        except ValueError:
            return None
    else:
        then = datetime.fromtimestamp(iso_or_mtime, tz=timezone.utc)
    if then.tzinfo is None:
        then = then.replace(tzinfo=timezone.utc)
    return round((datetime.now(timezone.utc) - then).total_seconds() / 86400, 1)


def porcelain_paths(output):
    """Paths from `git status --porcelain` output, handling renames."""
    paths = set()
    for line in (output or "").splitlines():
        parts = line.strip().split(None, 1)
        if len(parts) < 2:
            continue
        entry = parts[1]
        if " -> " in entry:
            old, _, new = entry.partition(" -> ")
            paths.add(old.strip())
            paths.add(new.strip())
        else:
            paths.add(entry.strip())
    return paths


def status_file(path, root):
    """Classify one context file: fresh | stale | broken."""
    rel = os.path.relpath(os.path.abspath(path), root)
    result = {
        "file": rel,
        "status": "fresh",
        "changed": [],
        "missing": [],
        "warnings": [],
        "tracked": False,
        "age_days": None,
    }
    abspath = os.path.join(root, rel)
    if not os.path.isfile(abspath):
        result["status"] = "broken"
        result["warnings"].append("context file does not exist")
        return result

    with open(abspath, encoding="utf-8") as f:
        text = f.read()
    refs = parse_references(text)
    fm = parse_frontmatter(text)

    anchor = git(["log", "-1", "--format=%H", "--", rel], cwd=root)
    result["tracked"] = bool(anchor)
    if anchor:
        result["age_days"] = age_days(git(["log", "-1", "--format=%cI", "--", rel], cwd=root))
    else:
        result["age_days"] = age_days(os.path.getmtime(abspath))
        result["warnings"].append(
            "context file is not git-tracked — staleness check falls back to file mtimes"
        )

    if git(["check-ignore", "-q", ".wisci"], cwd=root) is not None:
        result["warnings"].append(".wisci/ is gitignored — git history cannot archive context files")

    changed = set()
    for ref in refs:
        ref_abs = os.path.join(root, ref)
        if not os.path.exists(ref_abs):
            result["missing"].append(ref)
            continue
        if anchor:
            committed = git(["diff", "--name-only", "-M", anchor, "HEAD", "--", ref], cwd=root)
            if committed:
                changed.update(committed.splitlines())
            dirty = git(["status", "--porcelain", "--", ref], cwd=root)
            changed.update(porcelain_paths(dirty))
        else:
            if os.path.getmtime(ref_abs) > os.path.getmtime(abspath):
                changed.add(ref)
    result["changed"] = sorted(changed)

    # Primer-specific: directory topology drift.
    if fm.get("structure_hash"):
        current = structure_hash(root)
        if current and current != fm["structure_hash"]:
            result["changed"].append("<repo structure>")

    if result["missing"]:
        result["status"] = "broken"
    elif result["changed"]:
        result["status"] = "stale"
    return result


# ---------- store scanning ----------

def wisci_dir(root):
    return os.path.join(root, ".wisci")


def handoff_leaves(root):
    d = os.path.join(wisci_dir(root), "handoff")
    if not os.path.isdir(d):
        return []
    return sorted(
        os.path.join(d, f) for f in os.listdir(d) if f.endswith(".md")
    )


def stream_info(leaf, root):
    with open(leaf, encoding="utf-8") as f:
        fm = parse_frontmatter(f.read())
    slug = os.path.splitext(os.path.basename(leaf))[0]
    return {
        "file": os.path.relpath(leaf, root),
        "slug": slug,
        "status": fm.get("status", "active"),
        "updated": fm.get("updated", ""),
        "goal": fm.get("goal", ""),
    }


def scan(root):
    store = wisci_dir(root)
    out = {"root": root, "store": os.path.isdir(store), "files": [], "streams": []}
    if not out["store"]:
        return out
    targets = []
    ctx_dir = os.path.join(store, "context")
    if os.path.isdir(ctx_dir):
        targets += sorted(
            os.path.join(ctx_dir, f) for f in os.listdir(ctx_dir) if f.endswith(".md")
        )
    primer = os.path.join(store, "primer.md")
    if os.path.isfile(primer):
        targets.append(primer)
    leaves = handoff_leaves(root)
    for t in targets + leaves:
        out["files"].append(status_file(t, root))
    out["streams"] = [stream_info(l, root) for l in leaves]
    return out


# ---------- handoff index ----------

def build_index(root, list_only=False):
    streams = [stream_info(l, root) for l in handoff_leaves(root)]
    index_path = os.path.join(wisci_dir(root), "handoff.md")
    if list_only:
        return {"streams": streams}

    if len(streams) < 2:
        # Emergent rule: an index only earns its tokens past one stream.
        if os.path.isfile(index_path):
            with open(index_path, encoding="utf-8") as f:
                if GENERATED_MARKER in f.read():
                    os.remove(index_path)
        return {"streams": streams, "index": None}

    groups = {"active": [], "blocked": [], "done": []}
    for s in streams:
        groups.setdefault(s["status"], groups["active"]).append(s)
    counts = ", ".join(
        f"{len(v)} {k}" for k, v in groups.items() if v
    )
    lines = ["# Handoff Index", "", f"> {GENERATED_MARKER} {counts}.", ""]
    for key, title in (("active", "Active"), ("blocked", "Blocked"), ("done", "Done")):
        if groups[key]:
            lines.append(f"## {title}")
            for s in groups[key]:
                goal = s["goal"] or "(no goal set)"
                when = f" — {s['updated']}" if s["updated"] else ""
                lines.append(f"- [{s['slug']}](handoff/{s['slug']}.md): {goal}{when}")
            lines.append("")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return {"streams": streams, "index": os.path.relpath(index_path, root)}


# ---------- session status ----------

def session_status(root):
    """One-line store summary for the SessionStart hook. Empty when no store."""
    result = scan(root)
    if not result["store"] or not (result["files"] or result["streams"]):
        return ""
    ctx = [f for f in result["files"] if f["file"].startswith(".wisci/context/")]
    stale = [f for f in ctx if f["status"] == "stale"]
    broken = [f for f in ctx if f["status"] == "broken"]
    active = [s for s in result["streams"] if s["status"] == "active"]
    blocked = [s for s in result["streams"] if s["status"] == "blocked"]
    parts = []
    if ctx:
        notes = [f"{len(g)} {label}" for g, label in ((stale, "stale"), (broken, "broken")) if g]
        note = f" ({', '.join(notes)})" if notes else ""
        parts.append(f"{len(ctx)} context file{'s' if len(ctx) != 1 else ''}{note}")
    if active:
        parts.append(f"{len(active)} active stream{'s' if len(active) != 1 else ''}")
    if blocked:
        parts.append(f"{len(blocked)} blocked")
    if not parts:
        return ""
    return f"WISCI: {', '.join(parts)}. /select to load."


# ---------- self-tests ----------

def _sh(args, cwd):
    subprocess.run(args, cwd=cwd, check=True, capture_output=True, text=True)


def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def run_tests():
    import shutil
    import tempfile

    tmp = tempfile.mkdtemp(prefix="wisci-test-")
    checks = 0

    def ok(cond, label):
        nonlocal checks
        assert cond, f"FAIL: {label}"
        checks += 1

    try:
        _sh(["git", "init", "-q", "-b", "main"], tmp)
        _sh(["git", "config", "user.email", "t@t"], tmp)
        _sh(["git", "config", "user.name", "t"], tmp)

        _write(os.path.join(tmp, "src/a.py"), "a = 1\n")
        _write(os.path.join(tmp, "src/b.py"), "b = 1\n")
        ctx = os.path.join(tmp, ".wisci/context/topic.md")
        _write(ctx, (
            "# Topic\n\n## Findings\nUses `src/a.py:3` heavily.\n\n"
            "## References\n- `src/a.py` — main module\n- `src/b.py` — helper\n"
        ))
        _sh(["git", "add", "-A"], tmp)
        _sh(["git", "commit", "-qm", "init"], tmp)

        r = status_file(ctx, tmp)
        ok(r["status"] == "fresh" and r["tracked"], "fresh after commit")
        ok(parse_references(open(ctx).read()) == ["src/a.py", "src/b.py"], "ref parsing strips :line")

        # Committed change to a referenced file → stale.
        _write(os.path.join(tmp, "src/a.py"), "a = 2\n")
        _sh(["git", "commit", "-aqm", "change a"], tmp)
        r = status_file(ctx, tmp)
        ok(r["status"] == "stale" and "src/a.py" in r["changed"], "committed change detected")

        # Uncommitted (dirty) change → also stale.
        _write(ctx, open(ctx).read() + "\nRefreshed.\n")  # re-anchor ctx at new HEAD
        _sh(["git", "add", ctx], tmp)
        _sh(["git", "commit", "-qm", "refresh ctx"], tmp)
        r = status_file(ctx, tmp)
        ok(r["status"] == "fresh", "fresh after ctx refresh")
        _write(os.path.join(tmp, "src/b.py"), "b = 2  # dirty\n")
        r = status_file(ctx, tmp)
        ok(r["status"] == "stale" and "src/b.py" in r["changed"], "dirty working tree detected")
        _sh(["git", "checkout", "-q", "--", "src/b.py"], tmp)

        # Rename → old path missing → broken.
        _sh(["git", "mv", "src/a.py", "src/a2.py"], tmp)
        _sh(["git", "commit", "-qm", "rename"], tmp)
        r = status_file(ctx, tmp)
        ok(r["status"] == "broken" and "src/a.py" in r["missing"], "renamed-away ref is broken")
        _sh(["git", "mv", "src/a2.py", "src/a.py"], tmp)
        _sh(["git", "commit", "-qm", "rename back"], tmp)

        # Untracked context file → warning + mtime fallback.
        ctx2 = os.path.join(tmp, ".wisci/context/untracked.md")
        _write(ctx2, "# U\n\n## References\n- `src/b.py` — helper\n")
        r = status_file(ctx2, tmp)
        ok(not r["tracked"] and any("not git-tracked" in w for w in r["warnings"]),
           "untracked warning")

        # Structure hash: new directory changes it.
        h1 = structure_hash(tmp)
        _write(os.path.join(tmp, "newdir/x.py"), "x = 1\n")
        _sh(["git", "add", "-A"], tmp)
        _sh(["git", "commit", "-qm", "new dir"], tmp)
        ok(structure_hash(tmp) != h1, "structure hash changes on new dir")

        # Primer with stale structure hash → stale.
        primer = os.path.join(tmp, ".wisci/primer.md")
        _write(primer, f"---\nstructure_hash: {h1}\n---\n# Primer\n")
        _sh(["git", "add", "-A"], tmp)
        _sh(["git", "commit", "-qm", "primer"], tmp)
        r = status_file(primer, tmp)
        ok(r["status"] == "stale" and "<repo structure>" in r["changed"], "primer structure drift")

        # Index: emergent threshold.
        leaf1 = os.path.join(tmp, ".wisci/handoff/auth.md")
        _write(leaf1, "---\nstatus: active\nupdated: 2026-07-07\ngoal: fix auth\n---\n# H\n")
        r = build_index(tmp)
        ok(r["index"] is None and len(r["streams"]) == 1, "no index for single stream")
        leaf2 = os.path.join(tmp, ".wisci/handoff/ci.md")
        _write(leaf2, "---\nstatus: blocked\nupdated: 2026-07-01\ngoal: migrate CI\n---\n# H\n")
        r = build_index(tmp)
        idx = open(os.path.join(tmp, ".wisci/handoff.md")).read()
        ok(r["index"] and "## Active" in idx and "## Blocked" in idx, "index generated at 2 streams")
        ok("[auth](handoff/auth.md): fix auth" in idx, "index entry format")
        ok(GENERATED_MARKER in idx, "generated marker present")

        # Done stream moves groups; dropping to 1 stream removes index.
        _write(leaf2, "---\nstatus: done\nupdated: 2026-07-07\ngoal: migrate CI\n---\n# H\n")
        build_index(tmp)
        idx = open(os.path.join(tmp, ".wisci/handoff.md")).read()
        ok("## Done" in idx and "## Blocked" not in idx, "done grouping")
        os.remove(leaf2)
        r = build_index(tmp)
        ok(r["index"] is None and not os.path.exists(os.path.join(tmp, ".wisci/handoff.md")),
           "index removed below threshold")

        # index --list and session-status.
        ok(build_index(tmp, list_only=True)["streams"][0]["slug"] == "auth", "index --list")
        line = session_status(tmp)
        ok(line.startswith("WISCI:") and "1 active stream" in line, "session-status line")

        # Empty store → silent.
        empty = tempfile.mkdtemp(prefix="wisci-empty-")
        try:
            _sh(["git", "init", "-q"], empty)
            ok(session_status(empty) == "", "silent on empty store")
        finally:
            shutil.rmtree(empty)

        print(f"ALL TESTS PASSED ({checks} checks)")
    finally:
        shutil.rmtree(tmp)


# ---------- entry point ----------

def main(argv):
    cwd = os.getcwd()
    cmd = argv[1] if len(argv) > 1 else "scan"
    if cmd in ("test", "--test"):
        run_tests()
        return 0
    root = repo_root(cwd)
    if cmd == "status":
        if len(argv) < 3:
            print("usage: wisci.py status <file>", file=sys.stderr)
            return 2
        print(json.dumps(status_file(argv[2], root), indent=2))
    elif cmd == "scan":
        print(json.dumps(scan(root), indent=2))
    elif cmd == "index":
        print(json.dumps(build_index(root, list_only="--list" in argv), indent=2))
    elif cmd == "session-status":
        line = session_status(root)
        if line:
            print(line)
    elif cmd == "structure-hash":
        print(structure_hash(root) or "")
    else:
        print(f"unknown command: {cmd}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
